# pandas-many-to-one-project

You now have all the piecces to move towards completing and going beyond
the task I set in class. The task was:

"For each amphitheater with a Pleiades ID,
list that ID's ancient name(s) and chronological information
First step... what are the steps?"

At a minimum, write an SQL SELECT query that lists amphitheater IDs that have
Pleiades identifiers along with the chronological information that pleiades records

MORE INTERESTING AND HARDER: Write an SQL SELECT query that also lists the start column
from the chronogrps table.
So four columns at least: ramphs.id, chronogrps.start, pleiades.minDate, pleiades.maxDate

once you do this it's easy to imagine a visualization of the difference between the founding
of a city as indicated by pleiades and the construction of its amphitheater.
A histogram of this would be nice. I'd calculate the difference using panda.
(Or rather, that's how I did it.)

Or think of some other manipulation that goes a step beyond the "at a minumum" query.


Finally, as you ponder how to do the above, think about the conceptual range of DH as 
found in this week's readings and as experienced while manipulating data in this
ipython notebook. It's all DH and we love it all. How can theory and practice fit together?
What other readings we've been assigned are relevant. This is just fodder for conversation.

In [25]:
import pandas as pd
import sqlite3

ramphs = pd.read_csv("https://raw.githubusercontent.com/sfsheath/roman-amphitheaters/master/roman-amphitheaters.csv")
chronogrps = pd.read_csv("https://raw.githubusercontent.com/sfsheath/roman-amphitheaters/master/chronogrps.csv")
pleiades = pd.read_csv("https://raw.githubusercontent.com/isaw-ga-3024/isaw-ga-3024.github.io/master/heath-sebastian/pleiades-places.csv")

conn = sqlite3.connect(':memory:')

ramphs.to_sql('ramphs',conn,if_exists="replace")
chronogrps.to_sql('chronogrps', conn, if_exists="replace")
pleiades.to_sql('pleiades',conn,if_exists="replace")

In [57]:
ramphs['pleiades'] = ramphs['pleiades'].str.replace("http://pleiades.stoa.org/places/","")

ramphs['difference'] = (pleiades.minDate)

ramphs.to_sql('ramphs',conn,if_exists="replace")

In [59]:
#print(ramphs['difference']).head(5)

In [38]:
# ramphs, chronogrps, and pleiades are now pandas DataFrames

print(type(ramphs))
print(type(chronogrps))
print(type(pleiades))

# Again, these are pandas DataFrames, not sql tables!

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [92]:
pd.read_sql("""SELECT ramphs.id, ramphs.chronogrp, chronogrps.start, ramphs.label, ramphs.pleiades, pleiades.minDate, chronogrps.start - pleiades.minDate 
 FROM ramphs, chronogrps, pleiades
 WHERE (ramphs.pleiades !="None" AND ramphs.pleiades = pleiades.id)
    AND (ramphs.chronogrp = chronogrps.chronogrp)
ORDER BY ramphs.id""", conn)

,id,chronogrp,start,label,pleiades,minDate,chronogrps.start - pleiades.minDate
0,agenAmphitheater,Imperial,50,Agen,138169,-30.0,80.0
1,ainHedjahAmphitheater,Second Century,100,Ain Hedjah,314857,-30.0,130.0
2,ainToungaAmphitheater,Imperial,50,Ain Tounga,315207,-330.0,380.0
3,albaFucensAmphitheater,Julio-Claudian,-27,Alba Fucens,413005,-330.0,303.0
4,albegnaAmphitheater,Imperial,50,Albegna,157803,-30.0,80.0
5,aldburoughAmphitheater,Imperial,50,Aldburough,89209,-30.0,80.0
6,aleriaAmphitheater,Imperial,50,Aleria,472048,-750.0,800.0
7,allifaeAmphitheater,Imperial,50,Allifae,432658,-330.0,380.0
8,altinumAmphitheater,Imperial,50,Altinum,393374,-550.0,600.0
9,altripaldaAmphitheater,Republican,-70,Altripalda,432618,-330.0,260.0
10,amiensAmphitheater,Second Century,100,Amiens,109321,-330.0,430.0
11,anazarbusAmphitheater,Imperial,50,Anazarbus,658378,-330.0,380.0
12,anconaAmphitheater,Julio-Claudian,-27,Ancona,413014,-550.0,523.0
13,antiochAmphitheater,Republican,-70,Antioch,658381,-1750.0,1680.0
14,aostaAmphitheater,Julio-Claudian,-27,Aosta,383579,-30.0,3.0
15,aphrodisiasAmphitheater,Fourth Century,300,Aphrodisias,638753,-550.0,850.0
16,aquaeNeriAmphitheater,First Century,1,Aquae Neri,138185,-330.0,331.0
17,aquileiaAmphitheater,Imperial,50,Aquileia,187290,-330.0,380.0
18,aquincumCivilAmphitheater,Imperial,50,Aquincum (Civilian),197130,-30.0,80.0
19,aquincumMilitaryAmphitheater,Imperial,50,Aquincum (Military),197130,-30.0,80.0
20,aquinoAmphitheater,Imperial,50,Aquino,432695,-330.0,380.0
21,arezzoAmphitheater,Flavian,69,Arezzo,413032,-750.0,819.0
22,arlesAmphitheater,Flavian,69,Arles,148217,-750.0,819.0
23,arnsburgAmphitheater,Imperial,50,Arnsburg,118575,-30.0,80.0
24,ascoliPicenoAmphitheater,Imperial,50,Ascoli,413036,-550.0,600.0
25,assisiAmphitheatre,Imperial,50,Assisi,413037,-550.0,600.0
26,augustaBagiennorumAmphitheater,Julio-Claudian,-27,Augusta Bagiennorum,383578,-330.0,303.0
27,aurelumCommodianumAmphitheater,Second Century,100,Aurelium Commodianum,315084,-30.0,130.0
28,autunAmphitheater,Imperial,50,Autun,177460,-30.0,80.0
29,avellaAmphitheater,Republican,-70,Abella,432617,-330.0,260.0
...,...,...,...,...,...,...,...
227,teramoAmphitheater,Imperial,50,Teramo,413179,-750.0,800.0
228,terminiImereseAmphitheater,Flavian,69,Termini,462513,-550.0,619.0
229,terniAmphitheater,First Century,1,Terni,413178,-750.0,751.0
230,thaenaeAmphitheater,Imperial,50,Thaenae,324825,-330.0,380.0
231,thevesteAmphitheater,Flavian,69,Theveste,324831,-330.0,399.0
232,thibariAmphitheater,Imperial,50,Thibari,315201,-330.0,380.0
233,thysdrusAmphitheater,Post-Severan,235,Thysdrus (lg.),324835,-330.0,565.0
234,thysdrusSmallAmphitheater,Second Century,100,Thysdrus (Sm.),324835,-330.0,430.0
235,tiburAmphitheater,Imperial,50,Tibur,423081,-750.0,800.0
236,tigavaCastraAmphitheater,Second Century,100,Tigava Castra,295357,-30.0,130.0
237,tipasaAmphitheater,Late Second Century,150,Tipasa,295363,-550.0,700.0
238,todiAmphitheater,Imperial,50,Todi,423108,-750.0,800.0
239,tomen-y-murAmphitheater,Imperial,50,Tomen y Mur,142376597,-30.0,80.0
240,toulouseAmphitheater,Imperial,50,Toulouse,246694,-330.0,380.0
241,toursAmphitheater,Hadrianic,117,Tours,138255,-30.0,147.0
242,trierAmphitheater,Second Century,100,Trier,108894,-30.0,130.0
243,tusculumAmphitheater,Second Century,100,Tusculum,423108,-750.0,850.0
244,urbisagliaAmphitheater,Flavian,69,Urbs Salvia,413364,-330.0,399.0
245,uticaAmphitheater,Second Century,100,Utica,315248,-750.0,850.0
246,vastoAmphitheater,Imperial,50,Vasto,413171,-550.0,600.0
247,velleiaAmphitheater,Julio-Claudian,-27,Velleia,383811,-330.0,303.0
248,venosaAmphitheater,Imperial,50,Venosa,442847,-330.0,380.0
249,vercelliAmphitheater,Imperial,50,Vercelli,383815,-550.0,600.0
250,veronaAmphitheatre,Julio-Claudian,-27,Verona,383816,-30.0,3.0
251,viminaciumAmphitheater,Second Century,100,Viminacium,207549,-30.0,130.0
252,vindonissaAmphitheater,Flavian,69,Vindonissa,177661,-330.0,399.0
253,virunumAmphitheater,Imperial,50,Virunum,197583,-30.0,80.0
254,volterraAmphitheater,First Century,1,Volterra,403292,-750.0,751.0
255,xantenAmphitheater,Imperial,50,Xanten,108896,-30.0,80.0
256,yorkAmphitheater,Imperial,50,York,89175,-30.0,80.0

In [95]:
amphitheaters_sql = pd.read_sql("""SELECT ramphs.id, ramphs.chronogrp, chronogrps.start, ramphs.label, ramphs.pleiades, pleiades.minDate, chronogrps.start - pleiades.minDate 
 FROM ramphs, chronogrps, pleiades
 WHERE (ramphs.pleiades !="None" AND ramphs.pleiades = pleiades.id)
    AND (ramphs.chronogrp = chronogrps.chronogrp)
ORDER BY ramphs.id""", conn)


amphitheaters_sql.to_csv("amphitheaters_sql.csv")